language: node_js
dist: jammy
node_js:
  - 18

addons:
  sonarcloud:
    organization: "henrythasler"

script:
  - npm run test && sonar-scanner 

after_success:  
  - coveralls < coverage/lcov.info

before_deploy:
  - npm run build

deploy:
  skip_cleanup: true
  on:
    tags: true  
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
